<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_flow_purchase</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>c167290a-4ee6-480d-a950-24463c99ca06</testSuiteGuid>
   <testCaseLink>
      <guid>eb784bb7-40b4-4e43-b18f-b931168dd962</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_demolaze/TC_Add_to_cart/TC_add_one_product</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbbbb25b-84fb-4a0c-9cbf-cda8194a40f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2c7e1d9-3297-438d-8e88-c1e49b434262</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>193c0922-35b6-46a6-b015-f2ea3ccdd58a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_demolaze/TC_create_order/TC_submit_empty_fields</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4359097a-b915-43bf-bd92-b761407345ff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7365956e-9ac8-4c4b-a1d2-4a72790d4754</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_demolaze/TC_create_order/TC_create_order_from_cart</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e8a7077-3650-403d-a4fe-6c1f492ae2e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b0409e4-a77f-4e21-9a6f-444711bbf98a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2987057-dced-48d3-b056-06966245d3fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>198507e5-5a94-4c59-923e-9d38a54ed454</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19f7aa87-6f24-4c9d-b1a4-d8b713525c6d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c505516e-fc93-4397-b9f8-61f6ed1af6f3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
